config/routes.rb
Rails.application.routes.draw do
  root to: 'notes#index'

  get '/notes/new' => 'notes#new', as: :new_note
  post '/notes' => 'notes#create'

  get '/notes' => 'notes#index'
  get '/notes/:id' => 'notes#show', as: :note

  get '/notes/:id/edit' => 'notes#edit', as: :edit_note
  patch '/notes/:id' => 'notes#update', as: :update_note

  delete '/notes/:id/destroy' => 'notes#destroy', as: :destroy_note
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def new
    @note = Note.new
  end

  def create
    note = Note.new(note_params)
    note.save

    redirect_to notes_path
  end

  def index
    @notes = Note.all
  end

  def show
  end

  def edit
  end

  def update
    @note.update(note_params)

    redirect_to note_path(@note.id)
  end

  def destroy
    @note.destroy

    redirect_to notes_path
  end

  private

  def note_params
    params.require(:note).permit(:text)
  end

  def set_note
    @note = Note.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def link_to_notes
    link_to :notes, notes_path
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails101</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for(note) do |f| %>
  <%= f.text_field :text %>
  <%= f.submit :submit %>
<% end %>

app/views/notes/_note.html.erb
<p>
	<%= note.text %> - 
	<%= link_to :edit, edit_note_path(note.id) %> - 
	<%= link_to :delete, destroy_note_path(note.id), method: :delete %>
</p>

app/views/notes/edit.html.erb
<h1>Edit note</h1>

<%= render 'form', note: @note %>

<p><%= link_to_notes %></p>

app/views/notes/index.html.erb
<h1>Notes</h1>

<% @notes.each do |note| %>
	<%= render 'note', note: note %>
<% end %>

<p><%= link_to :new_note, new_note_path %></p>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form', note: @note %>

<p><%= link_to_notes %></p>

app/views/notes/show.html.erb
<h1>Note</h1>

<%= render 'note', note: @note %>

<p><%= link_to_notes %></p>